### ISSUE TITLE
请问CC视频的demo中用到切面编程AOP了吗

### ISSUE THREAD

**Issue by ColorDesert** [CCVideo/VOD_Android_SDK#1]
因为你们使用的aspectjrt-1.7.3.jar版本太低我们项目中使用的是1.8.9版本有冲突，所以需要弄清楚aspectjrt-1.7.3.jar是在demo中用到了，还是视频播放先关的jar用到了。根据情况做项目的兼容，谢谢！

**Comment by babyboy8989** [comment]
aspectjrt-1.7.3.jar主要用于视频压缩功能，在Demo中是上传视频时可以选择压缩，与视频播放无关
