### ISSUE TITLE
为什么你们项目里aspectjx，导致我们自己项目根本没法再次使用aspectjx

### ISSUE THREAD

**Issue by Dboy233** [CCVideo/VOD_Android_SDK#14]
为什么你们项目里aspectjx，导致我们自己项目根本没法再次使用aspectjx
![image](https://user-images.githubusercontent.com/37604230/96394139-d862a280-11f3-11eb-86e4-aad7027d0cfb.png)
真的很无语！。。

**Comment by WaterMelon2018** [comment]
是报了jar包重复的错误吗？

**Comment by Dboy233** [comment]
是的，jar包冲突

**Comment by WaterMelon2018** [comment]
compressvideo这个库是压缩视频用的，你有用到这个功能吗

**Comment by Dboy233** [comment]
压缩视频是上传服务器用到的把。如果是那就是用到了。因为这个模块不是我负责的。

**Comment by WaterMelon2018** [comment]
你问下负责这块的人，现在是什么情况

**Comment by Dboy233** [comment]
我看过代码了，有用到，上传视频的时候压缩过。

**Comment by WaterMelon2018** [comment]
现在这个冲突依然存在还是你们已经处理了呢？

**Comment by Dboy233** [comment]
我们项目放弃使用aspectjx，如果你们后续更新处理了这个问题。我们还是会增加使用的。这对我们的项目有i很大的帮助。

**Comment by WaterMelon2018** [comment]
Jar包重复冲突，只保留一个jar包，你验证一下功能是否正常。

**Comment by Dboy233** [comment]
我们已经决定把上传功能取消掉了。所以这一块代码我在整理重构中。
