### ISSUE TITLE
Fatal Error] vod-3.9.0.pom:2:10: 已经看到 doctype

### ISSUE THREAD

**Issue by Dboy233** [CCVideo/VOD_Android_SDK#16]
**Fatal Error] vod-3.9.0.pom:2:10: 已经看到 doctype**

**Comment by babyboy8989** [comment]
因为github访问速度受限，我们的SDK发布仓库已经迁移到自建仓库，麻烦您移步到下面链接，使用新版SDK。祝您工作顺利，生活愉快。

https://hdgit.bokecc.com/ccvideo/VOD_Android_SDK/-/releases
