### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by perfectnihil** [CCVideo/VOD_Android_SDK#2]
问几个问题
1. DWMediaPlayer  DWIjkMediaPlayer  
这两个类都是用来播放的，有什么区别

2. 这两个类有播放进度的回调吗？还是只能自己做定时器然后一直getCurrentPosition()

3. Andriod SDK     Andriod_SDK_DRM    Andriod_SDK_vr
这三个有什么区别  DRM  vr  指的是什么？

**Comment by WaterMelon2018** [comment]
1.DWMediaPlayer 无倍速播放功能，DWIjkMediaPlayer有倍速播放功能；

2.没有播放进度回调，更新进度要通过定时器；

3.Andriod SDK 是播放普通非加密视频，可以播放任何支持格式的其他非加密视频
Andriod_SDK_DRM是支持播放数字版权保护的视频，也就是加密视频，能播放CC定义的加密视频，其他播放器不能播放CC加密的视频；
Andriod_SDK_vr是播放支持播放VR视频的

**Comment by WaterMelon2018** [comment]
> 问几个问题
> 
> 1. DWMediaPlayer  DWIjkMediaPlayer
>    这两个类都是用来播放的，有什么区别
> 2. 这两个类有播放进度的回调吗？还是只能自己做定时器然后一直getCurrentPosition()
> 3. Andriod SDK     Andriod_SDK_DRM    Andriod_SDK_vr
>    这三个有什么区别  DRM  vr  指的是什么？

**Comment by WaterMelon2018** [comment]
1.DWMediaPlayer 无倍速播放功能，DWIjkMediaPlayer有倍速播放功能；

2.没有播放进度回调，更新进度要通过定时器；

3.Andriod SDK 是播放普通非加密视频，可以播放任何支持格式的其他非加密视频
Andriod_SDK_DRM是支持播放数字版权保护的视频，也就是加密视频，能播放CC定义的加密视频，其他播放器不能播放CC加密的视频；
Andriod_SDK_vr是播放支持播放VR视频的

**Comment by perfectnihil** [comment]
好的，谢谢
