### ISSUE TITLE
ijk库的疑问

### ISSUE THREAD

**Issue by limuyang2** [CCVideo/VOD_Android_SDK#7]
sdk中所使用的 ijk so文件是否都是标准的？有没有经过魔改？？

目前出现第三方sdk 的 ijk 冲突问题，需要取其一。

**Comment by WaterMelon2018** [comment]
so文件有略微改动，增加了对https地址的支持。

**Comment by WaterMelon2018** [comment]
so文件有略微改动，增加了对https地址的支持。

**Comment by limuyang2** [comment]
增加了openssl.sh 的编译是吧？

**Comment by limuyang2** [comment]
那我是否可以自行编译一个全量版本的 so 进行替换？

**Comment by WaterMelon2018** [comment]
建议使用SDK提供的，自行编译的话需要你验证SDK能否正常使用。
